---
application:
  name: "eng-zap-challenge-nodejs"
  project: "zap-engineering-victor"
  organization: "QoveryCommunity"
routers:
- name: "main-eng-zap-challenge-nodejs"
  routes:
  - application_name: "eng-zap-challenge-nodejs"
    paths:
    - "/*"
